DROP TABLE IF EXISTS "book";

DROP TABLE IF EXISTS "language";

DROP TABLE IF EXISTS "author";

DROP TABLE IF EXISTS "domain";

DROP TABLE IF EXISTS "publisher";

DROP TABLE IF EXISTS "order";

DROP TABLE IF EXISTS "user";

DROP TABLE IF EXISTS "userInfo";

DROP TABLE IF EXISTS "gender";

DROP TABLE IF EXISTS "shippingAddress";
